trigger:
- master

pool:
  name: 'LibraryAgent'  # Self-hosted agent havuzunuzun adı
  demands:
    - agent.name -equals agent

variables:
  solution: 'LibraryApp.sln'  # GitHub deposundaki çözüm dosyasının yolu
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  publishDirectory: '$(Build.ArtifactStagingDirectory)/publish'  # Yayınlanan dosyaların konumu

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build and Publish solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: 'x64'
    msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:publishUrl=$(publishDirectory) /p:Configuration=$(buildConfiguration) /verbosity:normal'
    enableDefaultLogger: false

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(publishDirectory)'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/drop'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'LibraryBackendService'  # Azure servis bağlantınızın adı
    appType: 'webApp'
    appName: 'kutuphaneapi'  # Azure App Service adınız
    package: '$(Build.ArtifactStagingDirectory)/drop'
